name: Build image and push to Docker Hub

on: [push, workflow_dispatch, repository_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build latest
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ secrets.DOCKER_PLATFORMS }}
          push: true
          tags: rshop/deploy-pipe:latest